import { EncryptionCodec } from '../temporal/codec'

// Fixture generated by Python's EncryptionCodec with secret_key='test-secret-key-for-codec':
//   inner payload = Payload(metadata={'encoding': b'json/plain'}, data=b'{"key":"value"}')
//   encrypted with Fernet using the same key derivation as posthog/temporal/common/codec.py
const PYTHON_FERNET_FIXTURE = {
    secretKey: 'test-secret-key-for-codec',
    // The Fernet token produced by Python's Fernet.encrypt(inner_payload.SerializeToString())
    encryptedTokenB64:
        'Z0FBQUFBQnByR1RoY3RKUjBsUDM5UmFmQ1ZqbFA2MUxKZng5RU5yaW9tWV9wclh3UEViZHpPQmtlbGhsQi0zMzVBWmFISURjY01maWpMaDJZWWF1U1B0UHlKa2xVV1NqTnd6ekFBLUM1eEo4TjBYalhabWpHN2h1RWhYNmFqOFEzUTNxMEtPV0Z1NFg9',
}

const te = new TextEncoder()
const td = new TextDecoder()

describe('EncryptionCodec', () => {
    const codec = new EncryptionCodec(PYTHON_FERNET_FIXTURE.secretKey)

    it('round-trips encode then decode', async () => {
        const original = {
            metadata: { encoding: te.encode('json/plain') },
            data: te.encode('{"hello":"world"}'),
        }

        const encoded = await codec.encode([original])
        expect(encoded).toHaveLength(1)
        expect(td.decode(encoded[0].metadata!['encoding']!)).toBe('binary/encrypted')

        const decoded = await codec.decode(encoded)
        expect(decoded).toHaveLength(1)
        expect(td.decode(decoded[0].metadata!['encoding']!)).toBe('json/plain')
        expect(td.decode(decoded[0].data!)).toBe('{"hello":"world"}')
    })

    it('decodes a legacy Fernet token encrypted by the Python EncryptionCodec', async () => {
        const encryptedToken = Buffer.from(PYTHON_FERNET_FIXTURE.encryptedTokenB64, 'base64')

        const outerPayload = {
            metadata: { encoding: te.encode('binary/encrypted') },
            data: encryptedToken,
        }

        const decoded = await codec.decode([outerPayload])
        expect(decoded).toHaveLength(1)
        expect(td.decode(decoded[0].metadata!['encoding']!)).toBe('json/plain')
        expect(td.decode(decoded[0].data!)).toBe('{"key":"value"}')
    })

    it('passes through payloads without encrypted encoding', async () => {
        const plainPayload = {
            metadata: { encoding: te.encode('json/plain') },
            data: te.encode('not encrypted'),
        }

        const decoded = await codec.decode([plainPayload])
        expect(decoded).toHaveLength(1)
        expect(decoded[0]).toBe(plainPayload)
    })

    it('passes through payloads with no metadata', async () => {
        const noMetadata = { data: te.encode('bare') }

        const decoded = await codec.decode([noMetadata])
        expect(decoded).toHaveLength(1)
        expect(decoded[0]).toBe(noMetadata)
    })

    it('handles multiple payloads in a single batch', async () => {
        const payloads = [
            { metadata: { encoding: te.encode('json/plain') }, data: te.encode('"a"') },
            { metadata: { encoding: te.encode('json/plain') }, data: te.encode('"b"') },
            { metadata: { encoding: te.encode('json/plain') }, data: te.encode('"c"') },
        ]

        const encoded = await codec.encode(payloads)
        expect(encoded).toHaveLength(3)
        encoded.forEach((p) => {
            expect(td.decode(p.metadata!['encoding']!)).toBe('binary/encrypted')
        })

        const decoded = await codec.decode(encoded)
        expect(decoded).toHaveLength(3)
        expect(td.decode(decoded[0].data!)).toBe('"a"')
        expect(td.decode(decoded[1].data!)).toBe('"b"')
        expect(td.decode(decoded[2].data!)).toBe('"c"')
    })

    it('handles empty payload array', async () => {
        expect(await codec.encode([])).toEqual([])
        expect(await codec.decode([])).toEqual([])
    })

    it('rejects tampered GCM ciphertext via auth tag', async () => {
        const original = {
            metadata: { encoding: te.encode('json/plain') },
            data: te.encode('secret'),
        }

        const encoded = await codec.encode([original])
        // Decode the base64url token, flip a ciphertext byte, re-encode
        const rawToken = Buffer.from(Buffer.from(encoded[0].data as Uint8Array).toString(), 'base64url')
        rawToken[40] ^= 0xff
        const tampered = Buffer.from(rawToken.toString('base64url'))

        const tamperedPayload = {
            metadata: { encoding: te.encode('binary/encrypted') },
            data: tampered,
        }

        await expect(codec.decode([tamperedPayload])).rejects.toThrow()
    })

    it('rejects tampered legacy Fernet ciphertext via HMAC', async () => {
        const encryptedToken = Buffer.from(PYTHON_FERNET_FIXTURE.encryptedTokenB64, 'base64')
        // Decode base64url, flip a ciphertext byte in the Fernet body, re-encode
        const rawToken = Buffer.from(Buffer.from(encryptedToken).toString(), 'base64url')
        rawToken[30] ^= 0xff
        const tampered = Buffer.from(rawToken.toString('base64url'))

        const tamperedPayload = {
            metadata: { encoding: te.encode('binary/encrypted') },
            data: tampered,
        }

        await expect(codec.decode([tamperedPayload])).rejects.toThrow('HMAC verification failed')
    })

    it('rejects GCM token that is too short', async () => {
        // Build a minimal buffer with GCM version byte but too short
        const shortGcm = Buffer.alloc(10)
        shortGcm[0] = 0x81
        const b64 = Buffer.from(shortGcm.toString('base64url'))

        const payload = {
            metadata: { encoding: te.encode('binary/encrypted') },
            data: b64,
        }

        await expect(codec.decode([payload])).rejects.toThrow('GCM token too short')
    })

    it('rejects legacy Fernet token that is too short', async () => {
        const tooShort = {
            metadata: { encoding: te.encode('binary/encrypted') },
            data: new Uint8Array(10),
        }

        await expect(codec.decode([tooShort])).rejects.toThrow('Fernet token too short')
    })

    it('round-trips with short secret keys (padding)', async () => {
        const shortCodec = new EncryptionCodec('ab')
        const original = {
            metadata: { encoding: te.encode('json/plain') },
            data: te.encode('test'),
        }

        const encoded = await shortCodec.encode([original])
        const decoded = await shortCodec.decode(encoded)
        expect(td.decode(decoded[0].data!)).toBe('test')
    })

    it('round-trips with long secret keys (truncation)', async () => {
        const longCodec = new EncryptionCodec('a'.repeat(100))
        const original = {
            metadata: { encoding: te.encode('json/plain') },
            data: te.encode('test'),
        }

        const encoded = await longCodec.encode([original])
        const decoded = await longCodec.decode(encoded)
        expect(td.decode(decoded[0].data!)).toBe('test')
    })

    it('produces base64url-encoded tokens with GCM version 0x81', async () => {
        const original = {
            metadata: { encoding: te.encode('json/plain') },
            data: te.encode('test'),
        }

        const encoded = await codec.encode([original])
        const b64Token = Buffer.from(encoded[0].data as Uint8Array).toString()
        const rawToken = Buffer.from(b64Token, 'base64url')
        expect(rawToken[0]).toBe(0x81)
    })
})
